# Generated by Django 3.1.4 on 2020-12-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('project_description', models.CharField(max_length=500)),
                ('project_url', models.TextField(blank=True)),
                ('project_photo', models.ImageField(default='media/images/default.jpg', upload_to='media/images/')),
                ('portfolio_url', models.TextField(blank=True)),
            ],
        ),
    ]
