# Generated by Django 3.1.4 on 2020-12-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsubmission',
            name='language_used',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
