# Generated by Django 3.1.4 on 2020-12-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puo', '0002_projectsubmission_language_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsubmission',
            name='project_photo',
            field=models.ImageField(blank=True, default='media/images/default.jpg', upload_to='media/images/'),
        ),
    ]
